
all:
	ghc --make -outputdir=.build/1 example1.hs -o example1 -Wall
	ghc --make -outputdir=.build/2 example2.hs -o example2 -Wall
	ghc --make -outputdir=.build/3 example3.hs -o example3 -Wall
	ghc --make -outputdir=.build/4 example4.hs -o example4 -Wall
	ghc --make -outputdir=.build/5 example5.hs -o example5 -Wall
	ghc --make -outputdir=.build/6 example6.hs -o example6 -Wall
